# Generated by Django 4.2.5 on 2024-11-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrarClientes', '0004_rename_id_pregunta_pregunta_id_preguntas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hechos',
            fields=[
                ('ID_HECHOS', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'HECHOS',
            },
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('ID_OPCIONES', models.AutoField(primary_key=True, serialize=False)),
                ('PROPOSITO', models.CharField(max_length=255)),
                ('PRESUPUESTO', models.CharField(max_length=255)),
                ('ALMACENAMIENTO', models.CharField(max_length=255)),
                ('RAM', models.CharField(max_length=255)),
                ('CAMARA', models.CharField(max_length=255)),
                ('BATERIA', models.CharField(max_length=255)),
                ('NOMBRE', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'OPCIONES',
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('ID_RECOMENDACION', models.AutoField(primary_key=True, serialize=False)),
                ('FECHA', models.DateField(auto_now_add=True)),
                ('ID_CLIENTE_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrarClientes.cliente')),
            ],
            options={
                'db_table': 'RECOMENDACION',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionXOpciones',
            fields=[
                ('ID_RECOMENDACIONXOPCIONES', models.AutoField(primary_key=True, serialize=False)),
                ('ID_OPCIONES_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitarRecomendacion.opciones')),
                ('ID_RECOMENDACION_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitarRecomendacion.recomendacion')),
            ],
            options={
                'db_table': 'RECOMENDACIONXOPCIONES',
            },
        ),
        migrations.CreateModel(
            name='HechosXOpciones',
            fields=[
                ('ID_HECHOSXOPCIONES', models.AutoField(primary_key=True, serialize=False)),
                ('ID_HECHOS_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitarRecomendacion.hechos')),
                ('ID_OPCIONES_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitarRecomendacion.opciones')),
            ],
            options={
                'db_table': 'HECHOSXOPCIONES',
            },
        ),
    ]
