# Generated by Django 4.2.5 on 2024-10-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_CLIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRES', models.CharField(max_length=255)),
                ('APELLIDOS', models.CharField(max_length=255)),
                ('CORREO', models.EmailField(max_length=255)),
            ],
            options={
                'db_table': 'CLIENTE',
            },
        ),
    ]
