# Generated by Django 4.2.5 on 2024-10-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('ID_PREGUNTA', models.AutoField(primary_key=True, serialize=False)),
                ('PREGUNTA', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PREGUNTA',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('ID_RESPUESTA', models.AutoField(primary_key=True, serialize=False)),
                ('ID_PREGUNTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrarClientes.pregunta')),
            ],
        ),
    ]
