# Generated by Django 4.2.5 on 2024-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarClientes', '0002_pregunta_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='RESPUESTA',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='respuesta',
            table='RESPUESTA',
        ),
    ]
