# Generated by Django 4.2.5 on 2024-10-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarClientes', '0003_respuesta_respuesta_alter_respuesta_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='ID_PREGUNTA',
            new_name='ID_PREGUNTAS',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='ID_RESPUESTA',
            new_name='ID_RESPUESTAS',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='ID_PREGUNTA',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='ID_PREGUNTAS',
            field=models.ForeignKey(db_column='ID_PREGUNTAS', default=1, on_delete=django.db.models.deletion.CASCADE, to='registrarClientes.pregunta'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='pregunta',
            table='PREGUNTAS',
        ),
        migrations.AlterModelTable(
            name='respuesta',
            table='RESPUESTAS',
        ),
    ]
