CREATE DATABASE EXPERT_SYSTEM_PHONES;
USE EXPERT_SYSTEM_PHONES;

-- BASE DE DATOS TRANSACCIONAL
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(255),
    APELLIDOS VARCHAR(255),
    CORREO VARCHAR(255)
); 

CREATE TABLE RECOMENDACION (
    ID_RECOMENDACION INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    FECHA DATE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE PREGUNTAS (
    ID_PREGUNTAS INT PRIMARY KEY AUTO_INCREMENT,
    PREGUNTA VARCHAR(255)
);

CREATE TABLE RESPUESTAS (
    ID_RESPUESTAS INT PRIMARY KEY AUTO_INCREMENT,
    ID_PREGUNTAS INT,
    RESPUESTA VARCHAR(255),
    FOREIGN KEY (ID_PREGUNTAS) REFERENCES PREGUNTAS(ID_PREGUNTAS)
);


-- PENDIENTE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
CREATE TABLE HIPOTESIS_RECOMENDACION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    OPCIONES_ID INT,
    RECOMENDACIONES_ID INT,
    FOREIGN KEY (OPCIONES_ID) REFERENCES OPCIONES(ID),
    FOREIGN KEY (RECOMENDACIONES_ID) REFERENCES RECOMENDACION(ID_RECOMENDACION)
);

-- BASE DE DATOS DE CONOCIMIENTO
CREATE TABLE HECHOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FILTRO VARCHAR(255)
);

CREATE TABLE OPCIONES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255),
    PROPOSITO VARCHAR(255),
    PRESUPUESTO VARCHAR(255),
    ALMACENAMIENTO VARCHAR(255),
    RAM VARCHAR(255),
    MEGAPIXELES VARCHAR(255),
    BATERIA VARCHAR(255)
);

CREATE TABLE HECHOSXOPCIONES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    HECHOS_ID INT,
    OPCIONES_ID INT,
    FOREIGN KEY (HECHOS_ID) REFERENCES HECHOS(ID),
    FOREIGN KEY (OPCIONES_ID) REFERENCES OPCIONES(ID)
); 

-- PROCEDURES FOR WEAK TABLES
DELIMITER //
 CREATE PROCEDURE REGISTRO_HECHOS_OPCIONES(
 IN FILTRO VARCHAR (255),
 IN NOMBRE VARCHAR(255),
 IN PROPOSITO VARCHAR(255),
 IN PRESUPUESTO VARCHAR(255),
 IN ALMACENAMIENTO VARCHAR(255),
 IN RAM VARCHAR(255),
 IN MEGAPIXELES VARCHAR(255),
 IN BATERIA VARCHAR(255)
 )
BEGIN

DECLARE ID_NUEVO_HECHOS INT;
DECLARE ID_NUEVO_OPCIONES INT;

INSERT INTO HECHOS (FILTRO) VALUES (FILTRO);
SET ID_NUEVO_HECHOS = LAST_INSERT_ID();

INSERT INTO OPCIONES (NOMBRE, PROPOSITO, PRESUPUESTO, ALMACENAMIENTO, RAM, MEGAPIXELES, BATERIA)
VALUES (NOMBRE, PROPOSITO, PRESUPUESTO, ALMACENAMIENTO, RAM, MEGAPIXELES, BATERIA);
SET ID_NUEVO_OPCIONES = LAST_INSERT_ID();

INSERT INTO HECHOSXOPCIONES (HECHOS_ID, OPCIONES_ID) VALUES (ID_NUEVO_HECHOS, ID_NUEVO_OPCIONES);
END //
DELIMITER ;
-- Registros via procedure

CALL REGISTRO_HECHOS_OPCIONES 
('1. ¿Cual es el proposito para el que usaria el celular?', 'XIAOMI Redmi 13C', 'Uso basico y productividad', '100.000$ - 500.000$','128 GigaBytes','4 GygaBytes','50 Megapixeles','5000 Mph');


SELECT * FROM HECHOS;
SELECT * FROM OPCIONES;
SELECT  H.FILTRO, O.NOMBRE FROM HECHOSXOPCIONES D
JOIN HECHOS H ON D.HECHOS_ID = H.ID
JOIN OPCIONES O ON D.OPCIONES_ID = O.ID;
-- INSERT'S FOR TABLES

-- INSERT FOR TABLE PREGUNTAS
INSERT INTO PREGUNTAS (PREGUNTA) VALUES ('¿Cual es el proposito para el que usaria el celular?');
INSERT INTO PREGUNTAS (PREGUNTA) VALUES ('¿Cual es el presupuesto que tiene para comprar el celular?');
-- PRESUPUESTO 1 DE CELULAR
INSERT INTO PREGUNTAS (PREGUNTA) VALUES ('¿Cual es el almacenamiento deseado para el celular?');
INSERT INTO PREGUNTAS (PREGUNTA) VALUES ('¿Cual es la capacidad de memoria RAM deseada para su celular?');
INSERT INTO PREGUNTAS (PREGUNTA) VALUES ('¿Cuantos Megapixeles desea que tenga la camara del celular?');
INSERT INTO PREGUNTAS (PREGUNTA) VALUES ('¿Cual es la capacidad de bateria que desea para el celular?');
-- PRESUPUESTO 2 DE CELULAR




-- INSERT FOR TABLE RESPUESTAS
-- respuestas pregunta de proposito del celular
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (1, 'Ninguna de las opciones es la que busco');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (1, 'Uso basico y productividad');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (1, 'Creador de contenido');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (1, 'Gamming y entretenimiento');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (1, 'Durabilidad');
-- respuestas pregunta de presupuesto del celular
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (2, '100.000$ - 500.000$');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (2, '500.000$ - 1.000.000$');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (2, '1.000.000$ - 2.000.000$');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (2, '2.000.000$ - 3.000.000$');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (2, '3.000.000$ - 5.000.000$');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (2, '5.000.000$ - MAS');
-- respuestas para pregunta almacenamiento deseado del celular
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (3, '64 GigaBytes'); 
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (3, '128 GigaBytes'); 
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (3, '256 GigaBytes');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (3, '512 GigaBytes');  
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (3, 'Ninguno de esos almacenamientos'); 
-- respuestass para pregunta ram 
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (4, '3 GygaBytes');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (4, '4 GygaBytes'); 
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (4, '6 GygaBytes');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (4, '8 GygaBytes');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (4, '12 GygaBytes');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (4, '16 GygaBytes');
--  respuestas para megapixeles en camara
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '8 Megapixeles');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '13 Megapixeles');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '48 Megapixeles');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '50 Megapixeles');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '100 Megapixeles');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '108 Megapixeles');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '12 Megapixeles');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '64 Megapixeles');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (5, '200 Megapixeles');

-- respuestas pregunta de capacidad de bateria
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '5000 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '5200 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '4000 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '6000 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '3110 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '4500 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '5800 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '3900 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '3877 Mph');
INSERT INTO RESPUESTAS (ID_PREGUNTAS, RESPUESTA) VALUES (6, '4400 Mph');
